import type { Metadata } from "next";
import "../styles/index.scss";

const isDev = process.env.NODE_ENV === "development";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={false}>{children}</body>
    </html>
  );
}
